### ISSUE TITLE
Stopped working after renaming relay contain underscore

### ISSUE THREAD

**Issue by SYJoeyChua** [nkh-lab/usb-relay-module#1]
After renaming the relay to "RL_SC", not able to use set_relay.exe to set channel or to rename it

**Comment by nkh-lab** [comment]
It was fixed within this commit https://github.com/nkh-lab/usb-relay-module/commit/5691782262b6b6b40b716287d979a68f715a2cd6

**Comment by nkh-lab** [comment]
And released in v2.2.0: https://github.com/nkh-lab/usb-relay-module/releases/tag/2.2.0

**Comment by SYJoeyChua** [comment]
its working now, thank you so much!
